version: 2.1
jobs:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
         fingerprints:
           - "1e:d9:f3:a7:51:35:47:e7:8f:e1:20:eb:a0:9b:cd:6c"
      - checkout
      - run:
         name: Setup
         command: |
           chmod 755 .circleci/deploy.sh
           ssh-keyscan 65.1.93.116 >> ~/.ssh/known_hosts
      - run: 
         name: develop
         command: |
           git pull origin develop
      - run:
         name: Deploy
         command: ./.circleci/deploy.sh
      - run:
         name: prod
         command: |
           chmod 755 .circleci/deploy_prod.sh
           ssh-keyscan 65.1.93.116 >> ~/.ssh/known_hosts
           git pull origin prod
           ./.circleci/deploy_prod.sh

workflows:
  workflow:
    jobs:
      - my-custom-executor
