version: 2.1
jobs:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
         fingerprints:
           - "1e:d9:f3:a7:51:35:47:e7:8f:e1:20:eb:a0:9b:cd:6c"
           - "81:f8:fa:dc:e4:67:a0:91:a7:20:30:1e:d4:28:29:6e"
      - checkout
      - run:
         name: Setup
         command: |
           chmod 755 .circleci/deploy.sh
           ssh-keyscan 65.1.93.116 >> ~/.ssh/known_hosts
      - run:
         name: Deploy
         command: ./.circleci/deploy.sh
      - run:
         name: prod
         command: |
           chmod 755 .circleci/deploy_prod.sh
           ssh-keyscan 15.206.89.136 >> ~/.ssh/known_hosts
           ./.circleci/deploy_prod.sh

workflows:
  workflow:
    jobs:
      - my-custom-executor
